import numpy as np

# قائمة الألعاب المعتمدة والمحفوظة
GAMES_LIST = [
    "Chicken Runner",
        "Chicken Cross That Road",
            "Chicken Dash 10000",
                "Chicken Crash 1xBet",
                    "CrossFire Chicken x5000",
                        "Mystake Chicken Game"
                        ]

                        def high_precision_analysis(history_data, selected_game=None):
                            """
                                تحليل عالي الدقة مفحوص ومحمي من الأخطاء البرمجية
                                    """
                                        # 1. التحقق من وجود بيانات كافية
                                            if not history_data or len(history_data) < 4:
                                                    return {"status": "error", "message": "يتطلب التحليل 4 قراءات على الأقل."}

                                                        # 2. التأكد من صحة نوع البيانات المدخلة
                                                            try:
                                                                    data = np.array(history_data, dtype=float)
                                                                            if np.any(data < 1.0):
                                                                                        return {"status": "error", "message": "المضاعفات يجب أن تكون أكبر من أو تساوي 1.0"}
                                                                                            except (ValueError, TypeError):
                                                                                                    return {"status": "error", "message": "تحتوي البيانات على قيم غير رقمية."}

                                                                                                        # 3. التحقق من اسم اللعبة
                                                                                                            validated_game = selected_game if selected_game in GAMES_LIST else "عام / غير محدد"

                                                                                                                n = len(data)

                                                                                                                    # 4. تصفية الشطحات العالية بـ Modified Z-Score
                                                                                                                        median = np.median(data)
                                                                                                                            mad = np.median(np.abs(data - median))

                                                                                                                                if mad != 0:
                                                                                                                                        modified_z = 0.6745 * (data - median) / mad
                                                                                                                                                filtered_data = np.where(np.abs(modified_z) > 3.0, median + (1.5 * mad), data)
                                                                                                                                                    else:
                                                                                                                                                            filtered_data = data

                                                                                                                                                                # 5. حساب المتوسط المتحرك المزدوج (Dual EMA)
                                                                                                                                                                    alpha_short = 2.0 / (min(n, 3) + 1)
                                                                                                                                                                        alpha_long = 2.0 / (n + 1)

                                                                                                                                                                            ema_short = filtered_data[0]
                                                                                                                                                                                ema_long = filtered_data[0]

                                                                                                                                                                                    for x in filtered_data[1:]:
                                                                                                                                                                                            ema_short = (x * alpha_short) + (ema_short * (1 - alpha_short))
                                                                                                                                                                                                    ema_long = (x * alpha_long) + (ema_long * (1 - alpha_long))

                                                                                                                                                                                                        # 6. حساب السلسلة المنخفضة المتتالية
                                                                                                                                                                                                            low_streak = 0
                                                                                                                                                                                                                for val in reversed(history_data):
                                                                                                                                                                                                                        if val <= 1.35:
                                                                                                                                                                                                                                    low_streak += 1
                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                        break

                                                                                                                                                                                                                                                            # 7. حساب التقلب والانحراف المعياري
                                                                                                                                                                                                                                                                std_dev = np.std(filtered_data)
                                                                                                                                                                                                                                                                    mean_val = np.mean(filtered_data)
                                                                                                                                                                                                                                                                        volatility = std_dev / (mean_val + 1e-6)

                                                                                                                                                                                                                                                                            # 8. حساب التوقع الموزون
                                                                                                                                                                                                                                                                                base_prediction = (ema_short * 0.65) + (ema_long * 0.35)

                                                                                                                                                                                                                                                                                    if low_streak >= 3:
                                                                                                                                                                                                                                                                                            adjusted_prediction = base_prediction * 1.10
                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                        adjusted_prediction = base_prediction

                                                                                                                                                                                                                                                                                                            # 9. تقييم الهدف الآمن ونسبة الثقة
                                                                                                                                                                                                                                                                                                                safe_target = max(1.05, round(float(min(adjusted_prediction, median)), 2))
                                                                                                                                                                                                                                                                                                                    predicted_val = round(float(adjusted_prediction), 2)
                                                                                                                                                                                                                                                                                                                        confidence_score = max(55.0, min(95.0, 100.0 - (volatility * 30.0)))

                                                                                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                                                                                    "status": "success",
                                                                                                                                                                                                                                                                                                                                            "game": validated_game,
                                                                                                                                                                                                                                                                                                                                                    "predicted_multiplier": predicted_val,
                                                                                                                                                                                                                                                                                                                                                            "safe_target": safe_target,
                                                                                                                                                                                                                                                                                                                                                                    "confidence": f"{round(confidence_score, 1)}%",
                                                                                                                                                                                                                                                                                                                                                                            "trend": "صاعد (Upward)" if ema_short >= ema_long else "مستقر/هابط (Stable)",
                                                                                                                                                                                                                                                                                                                                                                                    "risk_level": "منخفض" if volatility < 0.35 else "متوسط/مرتفع",
                                                                                                                                                                                                                                                                                                                                                                                            "consecutive_lows": low_streak
                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                # --- اختبار تشغيل الكود للتأكد من المخرجات ---
                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                    # تجربة مدخلات لـ 6 أدوار سابقة
                                                                                                                                                                                                                                                                                                                                                                                                        test_data = [1.15, 1.22, 1.10, 4.20, 1.18, 1.30]
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                # إجراء التحليل على إحدى الألعاب المعتمدة
                                                                                                                                                                                                                                                                                                                                                                                                                    result = high_precision_analysis(test_data, selected_game="CrossFire Chicken x5000")
                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                            print("--- نتيجة فحص الكود ---")
                                                                                                                                                                                                                                                                                                                                                                                                                                for key, value in result.items():
                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"{key}: {value}")
                                                                                                                                                                                                                                                                                                                                                                                                                                        